#pragma once
#include<Windows.h>

#pragma region PreInfo
// IMMERSIVE MODES
#define		LIGHT_TITLEBRUSH				false
#define		DARK_TITLEBRUSH					true

//LIGHT THEME
#define		DWM_LIGHT_BORDERCOLOR	(COLORREF)(RGB(52, 52, 52))
#define		DWM_LIGHT_CAPTIONCOLOR	(COLORREF)(RGB(220, 220, 220))
#define		DWM_LIGHT_TEXTCOLOR		(COLORREF)(RGB(30, 30, 30))

//DARK THEME
#define		DWM_DARK_BORDERCOLOR	(COLORREF)(RGB(52, 52, 52))
#define		DWM_DARK_CAPTIONCOLOR	(COLORREF)(RGB(48, 48, 48))
#define		DWM_DARK_TEXTCOLOR		(COLORREF)(RGB(255, 255, 255))
#pragma endregion

// All string info. You can modify it.
#define		STANDART_WINDOW_CLASSNAME		L"ONYX_WINDOWS"
#define		STANDART_WINDOW_NAME			L"Onyx Window"
#define		STANDART_TITLE_BRUSH			DARK_TITLEBRUSH
#define		STANDART_X_LOCATION				CW_USEDEFAULT
#define		STANDART_Y_LOCATION				CW_USEDEFAULT
#define		STANDART_WIDTH					1280
#define		STANDART_HEIGHT					720
#define		STANDART_BACKCOLOR				(HBRUSH)(2)
#define		STANDART_DWM_BORDERCOLOR		DWM_DARK_BORDERCOLOR
#define		STANDART_DWM_CAPTIONCOLOR		DWM_DARK_CAPTIONCOLOR
#define		STANDART_DWM_TEXTCOLOR			DWM_DARK_TEXTCOLOR
#define		STANDART_WINDOW_STYLES			WS_OVERLAPPEDWINDOW
#define		STANDART_WINDOW_EX_STYLES		WS_EX_OVERLAPPEDWINDOW
#define		GAME_WINDOW_STYLES				WS_CAPTION | WS_SYSMENU	| WS_MINIMIZEBOX
#define		GAME_WINDOW_EX_STYLES			0

#pragma region OutInfo
#define		STANDART_WIDTH_WITH_BORDER		(STANDART_WIDTH + 16)
#define		STANDART_HEIGHT_WITH_BORDER		(STANDART_HEIGHT + 16)
#pragma endregion